// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
using System.Threading;
using OpenQA.Selenium.Support.UI;
using com.edgewords.Amtrustcourse.Base_Classes;

namespace com.edgewords.Amtrustcourse.Test_Cases
{
    [TestFixture]
    public class StoresyncTest : Base_Classes.TestBaseClass
    {


        [Test, Order(3)]
        public void assertcheck()
        {
            Assert.That("Foo", Does.Match("^[X]"));
            
        }

        [Test, Order(2), Category("Code")]
        public void someothertest()
        {
            Assert.Pass("This passes");
        }

        [Test, Order(1), Category("Web"), Category("Blah")]
        public void storesync()
        {
            // Test name: storesync
            // Step # | name | target | value
            // 1 | open | /demo-site/ | 
            driver.Navigate().GoToUrl("https://www.edgewordstraining.co.uk/demo-site/");
            // 2 | setWindowSize | 1109x1040 | 
            //driver.Manage().Window.Size = new System.Drawing.Size(1109, 1040);
            // 3 | click | id=woocommerce-product-search-field-0 | 

            //dismiss store warning
            driver.FindElement(By.CssSelector(".woocommerce-store-notice__dismiss-link")).Click();

            driver.FindElement(By.Id("woocommerce-product-search-field-0")).Click();

            

            // 4 | type | id=woocommerce-product-search-field-0 | cap
            driver.FindElement(By.Id("woocommerce-product-search-field-0")).SendKeys("cap");

            string bodytext = driver.FindElement(By.TagName("body")).Text;
            Console.WriteLine(bodytext);

            int searchx = driver.FindElement(By.Id("woocommerce-product-search-field-0")).Location.X;
            Console.WriteLine("searchpos : " + searchx.ToString());

            // 5 | sendKeys | id=woocommerce-product-search-field-0 | ${KEY_ENTER}
            driver.FindElement(By.Id("woocommerce-product-search-field-0")).SendKeys(Keys.Enter);
            // 6 | click | name=add-to-cart | 
            driver.FindElement(By.Name("add-to-cart")).Click();
            // 7 | click | linkText=View cart | 
            driver.FindElement(By.LinkText("View cart")).Click();
            // 8 | click | linkText=× | 
            driver.FindElement(By.LinkText("×")).Click();
            // 9 | click | linkText=Return to shop | 
            //Thread.Sleep(5000); //Explicit - change for Ex Conditional

            WebDriverWait mywait = new WebDriverWait(driver, TimeSpan.FromSeconds(10));
            mywait.Until(drv => drv.FindElement(By.LinkText("Return to shop")).Displayed && drv.FindElement(By.LinkText("Return to shop")).Enabled);

            Thread.Sleep(1000);

            driver.FindElement(By.LinkText("Return to shop")).Click();
            // 10 | click | linkText=Home | 
            driver.FindElement(By.LinkText("Home")).Click();
        }
    }
}